version: '3'
services: 
    mongodb:
        container_name: mongodb
        image: 'mongo:latest'
        ports: 
            - "27017:27017"
            
    server:
        container_name: server
        restart: always
        build: ./server
        volumes: 
            - /app/node_modules
            - ./server:/app
        links: 
            - mongodb
        ports: 
            - "5000:5000"
    
    client:
        container_name: client
        build: 
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app  
        environment:
            - CHOKIDAR_USEPOLLING=true
        ports: 
            - "3000:3000"
        stdin_open: true