version: '3'
services: 
    mongodb:
        container_name: mongodb
        image: 'mongo:latest'
        ports: 
            - "27017:27017"
            
    server:
        container_name: hamrobazar-server
        restart: always
        build: ./server
        volumes: 
            - ./server:/app
        links: 
            - mongodb
        ports: 
            - "80:3000"